### ISSUE TITLE
Silently doesn't work

### ISSUE THREAD

**Issue by ostrolucky** [goodroot/github-action-slack-project-notifier#2]
So situation is that I move the card in project between columns and I expect to get Slack notification. This is not currently the case and I don't know why, tool doesn't provide much useful info.

`.github/notify.yml`
```yml
name: Slack Project Notifier

on:
  project_card:
    types: [moved]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: goodroot/github-action-slack-project-notifier@1.2
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PROJECT: api.github.com/projects/4784825
          TOKEN: ${{ secrets.SLACK_PROJECT_NOTIFIER_TOKEN }}
```
Output:
<img width="1005" alt="Screenshot 2020-12-23 at 15 39 22" src="https://user-images.githubusercontent.com/496233/103008198-08e8f480-4535-11eb-8a74-b54449750423.png">

It doesn't even try to attempt the token I use here:
<img width="742" alt="Screenshot 2020-12-23 at 15 40 38" src="https://user-images.githubusercontent.com/496233/103008306-36ce3900-4535-11eb-9bb3-7de97511306b.png">

**Comment by ostrolucky** [comment]
@goodroot

**Comment by freeslugs** [comment]
@ostrolucky maybe look into this one instead. worked for me. https://github.com/marketplace/actions/slack-notify. Note needs custom work to have it notify on the card movement.

**Comment by goodroot** [comment]
@ostrolucky Heya -- can you try adding the Project token as a secret instead of defining it explicitly?

**Comment by ostrolucky** [comment]
WDYM? That's what I do, check posted yml
```yml
          TOKEN: ${{ secrets.SLACK_PROJECT_NOTIFIER_TOKEN }}
```

**Comment by freeslugs** [comment]
@ostrolucky he means to go to github project secrets and add a env variable there.  

Btw I'm in the same boat as you I tried this and it didn't work for me.

**Comment by ostrolucky** [comment]
Yeah that's what I do of course.

<img width="949" alt="Screenshot 2021-01-15 at 19 55 32" src="https://user-images.githubusercontent.com/496233/104766921-a1a51580-576b-11eb-9e66-85a840b24563.png">


And I mean even if I don't, action should complain token is not filled/valid.

**Comment by goodroot** [comment]
Thanks guy, will look this weekend and get back to you with something useful. 👍

**Comment by goodroot** [comment]
My feeling is that the scoping is incorrect.

`${{ secrets.SLACK_PROJECT_NOTIFIER_TOKEN }}`

Ensure the above token looks like so:

![Screen Shot 2021-01-15 at 11 37 07 AM](https://user-images.githubusercontent.com/9484709/104770864-1e150580-5726-11eb-95a4-22fe3f8064ac.png)

**Comment by ostrolucky** [comment]
I've assigned all permissions I could to a token, no change unfortunately.

**Comment by freeslugs** [comment]
@goodroot maybe you can just add some more logs so we can better determine at what point it is not working?

**Comment by ostrolucky** [comment]
@freeslugs Would you be kind enough to post how did you configure https://github.com/marketplace/actions/slack-notify for card movement?

**Comment by freeslugs** [comment]
@ostrolucky sure! Again it logs all card movements and no details about the cards, so I'd much prefer this repo over the other one. But here's my code 🙃

```yml
# This is a basic workflow to help you get started with Actions

name: Slack

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  project_card:
    types: [moved]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
```


<img width="668" alt="image" src="https://user-images.githubusercontent.com/1843466/105228290-69695280-5b30-11eb-90d6-3b7f494b8cc0.png">
